
CREATE DATABASE TestCatalog SYSTEM USER PASSWORD "Infogix@1240";

CREATE USER harvestortestuser  PASSWORD Harvestortestuser01 NO FORCE_FIRST_PASSWORD_CHANGE;

GRANT DATA ADMIN TO  harvestortestuser;


CREATE USER harvestertestuser2  PASSWORD Harvestertestuser01 NO FORCE_FIRST_PASSWORD_CHANGE;
CREATE ROLE TESTCATALOGR;
GRANT TESTCATALOGR TO harvestertestuser2;
GRANT CATALOG READ TO TESTCATALOGR


GRANT SAP_INTERNAL_HANA_SUPPORT TO harvestertestuser4
